export const PATH = {
  home: '/',
  products: '/products',
  about: '/about',
  facebook: '/',
  twitter: '/',
  instagram: '/',
  tiktok: '/',
  pinterest: '/',
  brand: '/',
  history: '/',
  recruitment: '/',
  purchasedHistory: '/',
  cart: '/',
  informations: '/',
  payment: '/',
  handbook: '/',
  questions: '/',
};
