export const PATH = {
  home: '/',
  products: '/products',
  brandHistory: '/about/brand-history',
  recruitment: '/about/recruitment',
  register: '/auth/register',
  login: '/auth/login',
  forgotPassword: '/auth/forgot-password',
  resetPassword: '/auth/reset-password',
  facebook: '/',
  twitter: '/',
  instagram: '/',
  tiktok: '/',
  pinterest: '/',
  brand: '/',
  history: '/',
  recruitment: '/',
  purchasedHistory: '/',
  cart: '/',
  informations: '/',
  payment: '/',
  handbook: '/',
  questions: '/',
};
